fix installBiz need bizName and bizVersion
sofastack/sofa-serverless pull request #170
Opened 2023-10-17 08:41 UTC by sususama

### Motivation

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

### Modification

Describe the idea and modifications you've done.

### Result

Resolved or fixed #147 

If there is no issue then describe the changes introduced by this PR.

2023-10-17 08:46 UTC, lvjing2 commented
如果请求参数里没有，则从jar包里获取下

2023-10-17 08:47 UTC, sususama commented
> 如果请求参数里没有，则从jar包里获取下

在使用queryAllBiz查询的时候能得到jar包中的 bizName 和 bizVersion

2023-10-17 08:54 UTC, lvjing2 commented
不是说这两个变量不需要了，只是尽量让这两个变量从jar里获取，以免在用户错误输入的时候，与实际jar里不一致，导致一些体验问题。这两个参数在运维过程中会用到，需要在较早阶段获取到这两个变量。

2023-10-17 08:55 UTC, sususama commented
👌稍后我做修改

2023-10-17 13:08 UTC, sususama commented
现在初步的期望是不需要输入 `bizName` 和 `bizVersion` ，在 `InstallBizHandler` 的 `validate` 中根据 `bizUrl` 将`bizName` 和 `bizVersion`属性解析出来

2023-10-23 09:28 UTC, TomorJM requested changes
当前的变更, 是在执行ark install的时候会从文件中获取name和version, 但是在进入这个逻辑之前外面的锁逻辑依旧是用的用户输入的name和version, 这会真正锁的identity和真实安装的identity不一致, 锁控制逻辑参考 BizOpsCommandCoordinator

2023-10-23 09:28 UTC, TomorJM commented on sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/InstallBizHandler.java
> +        try {
这段代码能否单独抽成一个方法

2023-10-23 14:28 UTC, sususama commented
> 当前的变更, 是在执行ark install的时候会从文件中获取name和version, 但是在进入这个逻辑之前外面的锁逻辑依旧是用的用户输入的name和version, 这会真正锁的identity和真实安装的identity不一致, 锁控制逻辑参考 BizOpsCommandCoordinator


这块我的代码加在`validate`部分，这个部分并没有进入锁

2023-12-09 03:37 UTC, lvjing2 reviewed
LGTM

2023-12-09 09:29 UTC, merged